### ISSUE TITLE
Arrange the files in a better way

### ISSUE THREAD

**Issue by brion25** [jonaramos/github-repo-search#1]
Right now, everything lives under `src/app`, but I think you can arrange them better. Arrange all the components in a `components` folder, the `app-component` can stay in the same position as it is right now, since it's the entry point of the app.  `services` and `models` are in the correct folder.

**Comment by jonaramos** [comment]
I do like the idea of the components folder, but i aligned to the angular official [style guide](https://angular.io/guide/styleguide#style-04-06) for file structure.

> While components in dedicated folders are widely preferred, another option for small apps is to keep components flat (not in a dedicated folder). This adds up to four files to the existing folder, but also reduces the folder nesting. Whatever you choose, be consistent.

They recommend to include a components folder when you are above 4 components. This project has 3. But is just a guide i can move components to new folder expecting new components to be created.

Thank you for the suggestion, i will apply it on the next commit.

**Comment by jonaramos** [comment]
@brion25 Changes have been [commited](https://github.com/jonaramos/github-repo-search/pull/3/commits).
