### ISSUE TITLE
Do not inject HTML directly

### ISSUE THREAD

**Issue by brion25** [jonaramos/github-repo-search#2]
Do NOT pass HTML string as params to child components, pass the data and then format it inside that component

https://github.com/jonaramos/github-repo-search/blob/d267498cefeffc8db9eac0530b6353d3b923143b/src/app/git-search/git-search.component.ts#L84

**Comment by jonaramos** [comment]
There is a [RepoCommentComponent](https://github.com/jonaramos/github-repo-search/tree/master/src/app/repo-comment) to form the view, i forgot to replace the test dialog view with the comment component.

Thank you for your suggestion. I will apply it on the next commit.

**Comment by jonaramos** [comment]
@brion25 Changes have been [commited](https://github.com/jonaramos/github-repo-search/pull/3/commits).
